version: '3.7'

services:

  web:
    image: httpd:latest
    container_name: web
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: codopass123
      MYSQL_DATABASE: expense_db
    ports:
      - 3306:3306

  #adminer:
  #  image: adminer:latest
  #  environment:
  #    ADMINER_DEFAULT_SERVER: mysql
  #  ports:
  #     - 8080:8080

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
