# Generated by Django 5.0.7 on 2024-07-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("TRANSPORT", "Transport"),
                            ("HEALTH", "Health"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("EDUCATION", "Education"),
                            ("SERVICES", "Services"),
                            ("GENERAL", "General"),
                            ("OTHER", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("expense_detail", models.CharField(max_length=100)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("ARS", "Argentine Peso"),
                        ],
                        max_length=3,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
            ],
            options={
                "db_table": "expense_mysql",
            },
        ),
    ]
